FROM rust:1.58-bullseye as builder

WORKDIR /app

COPY .cargo .cargo/
COPY src src/
COPY Cargo.lock Cargo.toml ./

RUN cargo install --path .



FROM debian:bullseye

RUN apt-get update && apt-get install -y time

WORKDIR /app

COPY --from=builder /usr/local/cargo/bin/wordcount ./
COPY article.txt words.txt ./

ENTRYPOINT ["time", "./wordcount"]
CMD ["words.txt", "article.txt"]
